apiVersion: v1
kind: Service
metadata:
  name: {{ template "byteball-devnet.name" . }}-hub
  chart: {{ template "byteball-devnet.chart" . }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
  component: hub
spec:
  type: ClusterIP
  ports:
  - name: hub
    port: 6611
    targetPort: 6611
  selector:
    app: {{ template "byteball-devnet.name" . }}
    release: {{ .Release.Name }}
    component: hub
