{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "byteball-devnet.name" . }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    chart: {{ template "byteball-devnet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/volumes/byteball-devnet
    type: DirectoryOrCreate
{{- end }}
