apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "byteball-devnet.fullname" . }}-witness
  labels:
    app: {{ template "byteball-devnet.name" . }}
    chart: {{ template "byteball-devnet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: witness
data:
{{ toYaml .Values.witness.configuration | indent 2 }}
